'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 6/18/2018 4:10:53 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Collections.ObjectModel
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations
Imports System.Data
Imports System.Data.Common
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.ModelConfiguration
Imports System.Data.Entity.ModelConfiguration.Conventions
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports System.Data.Entity.Core.EntityClient
Imports System.Data.Entity.Core.Objects
Imports System.Data.Entity.Core.Objects.DataClasses

Namespace VNDataModel

    Public Partial Class VNDataEntities
      Inherits DbContext
        #Region "Constructors"
        ''' <summary>
        ''' Initialize a new VNDataEntities object.
        ''' </summary>
        Public Sub New()            
            MyBase.New("name=VNDataEntitiesConnectionString")
            Configure()
        End Sub

        ''' <summary>
        ''' Initializes a new VNDataEntities object using the connection string found in the 'VNDataEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New(connectionString As String)
            MyBase.New(connectionString)
            Configure()
        End Sub

        Private Sub Configure()
            Configuration.AutoDetectChangesEnabled = True
            Configuration.LazyLoadingEnabled = False
            Configuration.ProxyCreationEnabled = True
            Configuration.ValidateOnSaveEnabled = True
        End Sub

        #End Region

        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)

            Throw New UnintentionalCodeFirstException()
        End Sub

        #Region "DbSet Properties"
        ''' <summary>
        ''' There are no comments for JobType in the schema.
        ''' </summary>
        Public Overridable Property JobTypes() As DbSet(Of JobType)
        ''' <summary>
        ''' There are no comments for VNA057TB02Job in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB02Jobs() As DbSet(Of VNA057TB02Job)
        ''' <summary>
        ''' There are no comments for JobStep in the schema.
        ''' </summary>
        Public Overridable Property JobSteps() As DbSet(Of JobStep)
        ''' <summary>
        ''' There are no comments for VNA057TB04CustomerJobInfo in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB04CustomerJobInfos() As DbSet(Of VNA057TB04CustomerJobInfo)
        ''' <summary>
        ''' There are no comments for VNA057TB05CustomerJobStep in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB05CustomerJobSteps() As DbSet(Of VNA057TB05CustomerJobStep)
        ''' <summary>
        ''' There are no comments for VNA057VW01JobNotPrinted in the schema.
        ''' </summary>
        Public Overridable Property VNA057VW01JobNotPrinteds() As DbSet(Of VNA057VW01JobNotPrinted)
        #End Region
    End Class
End Namespace
