'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 2022/06/29 2:44:18 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class TableJob 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property JobId() As Integer
    
        Public Overridable Property JobTypeId() As Integer
    
        Public Overridable Property KNDY4CustomerC1() As String
    
        Public Overridable Property KNDY4SalesOrderC1() As String
    
        Public Overridable Property Printed() As Boolean
    
        Public Overridable Property SalesOrderName() As String
    
        Public Overridable Property CustomerName() As String
    
        Public Overridable Property Reprint() As Boolean?
    
        Public Overridable Property CreatedDate() As Global.System.DateTime?
    
        Public Overridable Property VNStoreNumberC() As String
    
        Public Overridable Property VNOrderTypeC() As String
    
        Public Overridable Property LabelCount() As Integer?

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property JobType() As TableJobType

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
