'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 3/15/2019 1:55:00 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class ViewPalletJobsNotPrinted 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property JobTypeId() As Integer
    
        Public Overridable Property JobId() As Integer
    
        Public Overridable Property KNDY4CustomerC() As String
    
        Public Overridable Property CustomerName() As String
    
        Public Overridable Property SalesOrder() As String
    
        Public Overridable Property SalesOrderName() As String
    
        Public Overridable Property ShipmentData() As Global.System.DateTime?
    
        Public Overridable Property Expr1() As Integer

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
