'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 9/4/2018 1:42:30 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    ''' <summary>
    ''' There are no comments for VNDataModel.TableCustomerJobStep in the schema.
    ''' </summary>
    Public partial class TableCustomerJobStep 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' There are no comments for CustomerJobStepsId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobStepsId() As Integer
    
        ''' <summary>
        ''' There are no comments for CustomerJobInfoId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobInfoId() As Integer
    
        ''' <summary>
        ''' There are no comments for JobStepId in the schema.
        ''' </summary>
        Public Overridable Property JobStepId() As Integer
    
        ''' <summary>
        ''' There are no comments for PrinterCompatibilityID in the schema.
        ''' </summary>
        Public Overridable Property PrinterCompatibilityID() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelSizeId in the schema.
        ''' </summary>
        Public Overridable Property LabelSizeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for SourceTypeId in the schema.
        ''' </summary>
        Public Overridable Property SourceTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for DeliveryTypeId in the schema.
        ''' </summary>
        Public Overridable Property DeliveryTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelOrientationId in the schema.
        ''' </summary>
        Public Overridable Property LabelOrientationId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelCount in the schema.
        ''' </summary>
        Public Overridable Property LabelCount() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for PrinterId in the schema.
        ''' </summary>
        Public Overridable Property PrinterId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for FormatName in the schema.
        ''' </summary>
        Public Overridable Property FormatName() As String
    
        ''' <summary>
        ''' There are no comments for DateCreated in the schema.
        ''' </summary>
        Public Overridable Property DateCreated() As Global.System.Nullable(Of System.DateTime)

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' There are no comments for JobStep in the schema.
        ''' </summary>
        Public Overridable Property JobStep() As TableJobStep
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_PrinterCompatibilityID in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_PrinterCompatibilityID() As TableTypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_LabelSizeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_LabelSizeId() As TableTypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_SourceTypeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_SourceTypeId() As TableTypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_DeliveryTypeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_DeliveryTypeId() As TableTypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_LabelOrientationId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_LabelOrientationId() As TableTypeCode

        #End Region
    
        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
