'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 11/19/2018 11:18:38 AM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    ''' <summary>
    ''' There are no comments for VNDataModel.ViewSalesOrder in the schema.
    ''' </summary>
    Public partial class ViewSalesOrder 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' There are no comments for KNDY4StatusC in the schema.
        ''' </summary>
        Public Overridable Property KNDY4StatusC() As String
    
        ''' <summary>
        ''' There are no comments for Name in the schema.
        ''' </summary>
        Public Overridable Property Name() As String
    
        ''' <summary>
        ''' There are no comments for SalesOrderId in the schema.
        ''' </summary>
        Public Overridable Property SalesOrderId() As String
    
        ''' <summary>
        ''' There are no comments for SONo in the schema.
        ''' </summary>
        Public Overridable Property SONo() As String
    
        ''' <summary>
        ''' There are no comments for ShipmentDate in the schema.
        ''' </summary>
        Public Overridable Property ShipmentDate() As Global.System.DateTime?
    
        ''' <summary>
        ''' There are no comments for CustomerID in the schema.
        ''' </summary>
        Public Overridable Property CustomerID() As String
    
        ''' <summary>
        ''' There are no comments for CustomerName in the schema.
        ''' </summary>
        Public Overridable Property CustomerName() As String
    
        ''' <summary>
        ''' There are no comments for LineNo in the schema.
        ''' </summary>
        Public Overridable Property LineNo() As Decimal?
    
        ''' <summary>
        ''' There are no comments for ProductName in the schema.
        ''' </summary>
        Public Overridable Property ProductName() As String

        #End Region
    
        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
