'------------------------------------------------------------------------------
' This is auto-generated code.
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
' Code is generated on: 7/6/2018 3:30:08 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System.Collections.Generic
Imports System.Data.Entity.Core.Metadata.Edm
Imports System.Data.Entity.Infrastructure.MappingViews

<assembly: DbMappingViewCacheTypeAttribute(GetType(VNDataModel.VNDataEntities), GetType(EntityMappingGeneratedViews.ViewsForBaseEntitySets91758f5e97834e6ca4ee0237cc5c27a1))>
	
Namespace EntityMappingGeneratedViews

    <System.CodeDom.Compiler.GeneratedCode("Devart Entity Developer", "")> _
	Public Class ViewsForBaseEntitySets91758f5e97834e6ca4ee0237cc5c27a1
	  Inherits DbMappingViewCache
	
		Private Shared cachedViews As Dictionary(Of string, DbMappingView) = Nothing
		Private Shared syncRoot = New object()

		Public Sub New()
		End Sub
		
		Public Overrides ReadOnly Property MappingHashValue As String
		  Get
 		    Return "6494318bda3ee37b0d5ffc3a30ce28921a5d0f9fb8110eca9897bc1d3e4b0b56"
		  End Get
	    End Property

		Public Overrides Function GetView(entitySet As EntitySetBase) As DbMappingView
		
			If (cachedViews Is Nothing) Then
			  SyncLock syncRoot
			    If (cachedViews Is Nothing) Then
			      FillCache()
				End If
			  End SyncLock
			End If

			Dim view As DbMappingView = Nothing
			cachedViews.TryGetValue(entitySet.EntityContainer.Name + "." + entitySet.Name, view)
			Return view
		End Function

		Private Shared Sub FillCache()

			cachedViews = New Dictionary(Of String, DbMappingView)()
			cachedViews.Add("VNDataEntitiesStoreContainer.JobTypes", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing JobTypes" & vbNewLine &
"        [VNDataModel.Store.JobTypes](T1.JobTypes_JobTypeId, T1.JobTypes_JobTypeName, T1.JobTypes_DLLName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS JobTypes_JobTypeId, " & vbNewLine &
"            T.JobTypeName AS JobTypes_JobTypeName, " & vbNewLine &
"            T.DLLName AS JobTypes_DLLName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.JobTypes AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.Jobs", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing Jobs" & vbNewLine &
"        [VNDataModel.Store.Jobs](T1.Jobs_JobId, T1.Jobs_JobTypeId, T1.[Jobs.KNDY4__Customer__c], T1.[Jobs.KNDY4__Sales_Order__c], T1.Jobs_Printed, T1.Jobs_SalesOrderName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobId AS Jobs_JobId, " & vbNewLine &
"            T.JobTypeId AS Jobs_JobTypeId, " & vbNewLine &
"            T.KNDY4CustomerC1 AS [Jobs.KNDY4__Customer__c], " & vbNewLine &
"            T.KNDY4SalesOrderC1 AS [Jobs.KNDY4__Sales_Order__c], " & vbNewLine &
"            T.Printed AS Jobs_Printed, " & vbNewLine &
"            T.SalesOrderName AS Jobs_SalesOrderName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.Jobs AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.JobSteps", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing JobSteps" & vbNewLine &
"        [VNDataModel.Store.JobSteps](T1.JobSteps_JobStepId, T1.JobSteps_JobTypeId, T1.JobSteps_JobStepName, T1.JobSteps_JobStepOrder, T1.JobSteps_LabelCount, T1.JobSteps_LabelType)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobStepId AS JobSteps_JobStepId, " & vbNewLine &
"            T.JobTypeId AS JobSteps_JobTypeId, " & vbNewLine &
"            T.JobStepName AS JobSteps_JobStepName, " & vbNewLine &
"            T.JobStepOrder AS JobSteps_JobStepOrder, " & vbNewLine &
"            T.LabelCount AS JobSteps_LabelCount, " & vbNewLine &
"            T.LabelType AS JobSteps_LabelType, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.JobSteps AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.CustomerJobInfos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerJobInfos" & vbNewLine &
"        [VNDataModel.Store.CustomerJobInfos](T1.CustomerJobInfos_CustomerJobInfoId, T1.[CustomerJobInfos.KNDY4__Customer__c], T1.CustomerJobInfos_JobTypeId, T1.CustomerJobInfos_CustomerName, T1.CustomerJobInfos_CustomerShortName, T1.CustomerJobInfos_Serialized, T1.CustomerJobInfos_PrinterId)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.CustomerJobInfoId AS CustomerJobInfos_CustomerJobInfoId, " & vbNewLine &
"            T.KNDY4CustomerC1 AS [CustomerJobInfos.KNDY4__Customer__c], " & vbNewLine &
"            T.JobTypeId AS CustomerJobInfos_JobTypeId, " & vbNewLine &
"            T.CustomerName AS CustomerJobInfos_CustomerName, " & vbNewLine &
"            T.CustomerShortName AS CustomerJobInfos_CustomerShortName, " & vbNewLine &
"            T.Serialized AS CustomerJobInfos_Serialized, " & vbNewLine &
"            T.PrinterId AS CustomerJobInfos_PrinterId, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.CustomerJobInfos AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.CustomerJobSteps", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerJobSteps" & vbNewLine &
"        [VNDataModel.Store.CustomerJobSteps](T1.CustomerJobSteps_CustomerJobStepsId, T1.CustomerJobSteps_CustomerJobInfoId, T1.CustomerJobSteps_JobStepId, T1.CustomerJobSteps_PrinterCompatibilityID, T1.CustomerJobSteps_LabelSizeId, T1.CustomerJobSteps_SourceTypeId, T1.CustomerJobSteps_DeliveryTypeId, T1.CustomerJobSteps_LabelOrientationId, T1.CustomerJobSteps_LabelCount, T1.CustomerJobSteps_PrinterId)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.CustomerJobStepsId AS CustomerJobSteps_CustomerJobStepsId, " & vbNewLine &
"            T.CustomerJobInfoId AS CustomerJobSteps_CustomerJobInfoId, " & vbNewLine &
"            T.JobStepId AS CustomerJobSteps_JobStepId, " & vbNewLine &
"            T.PrinterCompatibilityID AS CustomerJobSteps_PrinterCompatibilityID, " & vbNewLine &
"            T.LabelSizeId AS CustomerJobSteps_LabelSizeId, " & vbNewLine &
"            T.SourceTypeId AS CustomerJobSteps_SourceTypeId, " & vbNewLine &
"            T.DeliveryTypeId AS CustomerJobSteps_DeliveryTypeId, " & vbNewLine &
"            T.LabelOrientationId AS CustomerJobSteps_LabelOrientationId, " & vbNewLine &
"            T.LabelCount AS CustomerJobSteps_LabelCount, " & vbNewLine &
"            T.PrinterId AS CustomerJobSteps_PrinterId, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.CustomerJobSteps AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057TB06_Types", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057TB06_Types" & vbNewLine &
"        [VNDataModel.Store.VNA057TB06_Types](T1.[VNA057TB06_Types.TypeId], T1.[VNA057TB06_Types.TypeName])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeId AS [VNA057TB06_Types.TypeId], " & vbNewLine &
"            T.TypeName AS [VNA057TB06_Types.TypeName], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.Types AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057TB07_TypeCodes", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057TB07_TypeCodes" & vbNewLine &
"        [VNDataModel.Store.VNA057TB07_TypeCodes](T1.[VNA057TB07_TypeCodes.TypeCodeId], T1.[VNA057TB07_TypeCodes.TypeCodeTypeId], T1.[VNA057TB07_TypeCodes.TypeCode], T1.[VNA057TB07_TypeCodes.TypeCodeName])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeCodeId AS [VNA057TB07_TypeCodes.TypeCodeId], " & vbNewLine &
"            T.TypeCodeTypeId AS [VNA057TB07_TypeCodes.TypeCodeTypeId], " & vbNewLine &
"            T.TypeCode AS [VNA057TB07_TypeCodes.TypeCode], " & vbNewLine &
"            T.TypeCodeName AS [VNA057TB07_TypeCodes.TypeCodeName], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.TypeCodes AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.JobTypes", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing JobTypes" & vbNewLine &
"        [VNDataModel.JobType](T1.JobType_JobTypeId, T1.JobType_JobTypeName, T1.JobType_DLLName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS JobType_JobTypeId, " & vbNewLine &
"            T.JobTypeName AS JobType_JobTypeName, " & vbNewLine &
"            T.DLLName AS JobType_DLLName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.JobTypes AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.Jobs", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing Jobs" & vbNewLine &
"        [VNDataModel.Job](T1.Job_JobId, T1.Job_JobTypeId, T1.Job_KNDY4CustomerC1, T1.Job_KNDY4SalesOrderC1, T1.Job_Printed, T1.Job_SalesOrderName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobId AS Job_JobId, " & vbNewLine &
"            T.JobTypeId AS Job_JobTypeId, " & vbNewLine &
"            T.KNDY4__Customer__c AS Job_KNDY4CustomerC1, " & vbNewLine &
"            T.KNDY4__Sales_Order__c AS Job_KNDY4SalesOrderC1, " & vbNewLine &
"            T.Printed AS Job_Printed, " & vbNewLine &
"            T.SalesOrderName AS Job_SalesOrderName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.Jobs AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.JobSteps", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing JobSteps" & vbNewLine &
"        [VNDataModel.JobStep](T1.JobStep_JobStepId, T1.JobStep_JobTypeId, T1.JobStep_JobStepName, T1.JobStep_JobStepOrder, T1.JobStep_LabelCount, T1.JobStep_LabelType)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobStepId AS JobStep_JobStepId, " & vbNewLine &
"            T.JobTypeId AS JobStep_JobTypeId, " & vbNewLine &
"            T.JobStepName AS JobStep_JobStepName, " & vbNewLine &
"            T.JobStepOrder AS JobStep_JobStepOrder, " & vbNewLine &
"            T.LabelCount AS JobStep_LabelCount, " & vbNewLine &
"            T.LabelType AS JobStep_LabelType, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.JobSteps AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.CustomerJobInfos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerJobInfos" & vbNewLine &
"        [VNDataModel.CustomerJobInfo](T1.CustomerJobInfo_CustomerJobInfoId, T1.CustomerJobInfo_KNDY4CustomerC1, T1.CustomerJobInfo_JobTypeId, T1.CustomerJobInfo_CustomerName, T1.CustomerJobInfo_CustomerShortName, T1.CustomerJobInfo_Serialized, T1.CustomerJobInfo_PrinterId)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.CustomerJobInfoId AS CustomerJobInfo_CustomerJobInfoId, " & vbNewLine &
"            T.KNDY4__Customer__c AS CustomerJobInfo_KNDY4CustomerC1, " & vbNewLine &
"            T.JobTypeId AS CustomerJobInfo_JobTypeId, " & vbNewLine &
"            T.CustomerName AS CustomerJobInfo_CustomerName, " & vbNewLine &
"            T.CustomerShortName AS CustomerJobInfo_CustomerShortName, " & vbNewLine &
"            T.Serialized AS CustomerJobInfo_Serialized, " & vbNewLine &
"            T.PrinterId AS CustomerJobInfo_PrinterId, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.CustomerJobInfos AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.CustomerJobSteps", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerJobSteps" & vbNewLine &
"        [VNDataModel.CustomerJobStep](T1.CustomerJobStep_CustomerJobStepsId, T1.CustomerJobStep_CustomerJobInfoId, T1.CustomerJobStep_JobStepId, T1.CustomerJobStep_PrinterCompatibilityID, T1.CustomerJobStep_LabelSizeId, T1.CustomerJobStep_SourceTypeId, T1.CustomerJobStep_DeliveryTypeId, T1.CustomerJobStep_LabelOrientationId, T1.CustomerJobStep_LabelCount, T1.CustomerJobStep_PrinterId)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.CustomerJobStepsId AS CustomerJobStep_CustomerJobStepsId, " & vbNewLine &
"            T.CustomerJobInfoId AS CustomerJobStep_CustomerJobInfoId, " & vbNewLine &
"            T.JobStepId AS CustomerJobStep_JobStepId, " & vbNewLine &
"            T.PrinterCompatibilityID AS CustomerJobStep_PrinterCompatibilityID, " & vbNewLine &
"            T.LabelSizeId AS CustomerJobStep_LabelSizeId, " & vbNewLine &
"            T.SourceTypeId AS CustomerJobStep_SourceTypeId, " & vbNewLine &
"            T.DeliveryTypeId AS CustomerJobStep_DeliveryTypeId, " & vbNewLine &
"            T.LabelOrientationId AS CustomerJobStep_LabelOrientationId, " & vbNewLine &
"            T.LabelCount AS CustomerJobStep_LabelCount, " & vbNewLine &
"            T.PrinterId AS CustomerJobStep_PrinterId, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.CustomerJobSteps AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.Types", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing Types" & vbNewLine &
"        [VNDataModel.Type](T1.Type_TypeId, T1.Type_TypeName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeId AS Type_TypeId, " & vbNewLine &
"            T.TypeName AS Type_TypeName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057TB06_Types AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.TypeCodes", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing TypeCodes" & vbNewLine &
"        [VNDataModel.VNA057TB07TypeCode](T1.VNA057TB07TypeCode_TypeCodeId, T1.VNA057TB07TypeCode_TypeCodeTypeId, T1.VNA057TB07TypeCode_TypeCode, T1.VNA057TB07TypeCode_TypeCodeName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeCodeId AS VNA057TB07TypeCode_TypeCodeId, " & vbNewLine &
"            T.TypeCodeTypeId AS VNA057TB07TypeCode_TypeCodeTypeId, " & vbNewLine &
"            T.TypeCode AS VNA057TB07TypeCode_TypeCode, " & vbNewLine &
"            T.TypeCodeName AS VNA057TB07TypeCode_TypeCodeName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057TB07_TypeCodes AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.CustomerSoldTos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerSoldTos" & vbNewLine &
"        [VNDataModel.Store.CustomerSoldTos](T1.CustomerSoldTos_Id, T1.CustomerSoldTos_Name)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.Id AS CustomerSoldTos_Id, " & vbNewLine &
"            T.Name AS CustomerSoldTos_Name, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.CustomerSoldTos AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.CustomerSoldTos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing CustomerSoldTos" & vbNewLine &
"        [VNDataModel.CustomerSoldTo](T1.CustomerSoldTo_Id, T1.CustomerSoldTo_Name)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.Id AS CustomerSoldTo_Id, " & vbNewLine &
"            T.Name AS CustomerSoldTo_Name, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.CustomerSoldTos AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057VW01_Job_Not_Printeds", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057VW01_Job_Not_Printeds" & vbNewLine &
"        [VNDataModel.Store.VNA057VW01_Job_Not_Printed](T1.[VNA057VW01_Job_Not_Printed.JobTypeId], T1.[VNA057VW01_Job_Not_Printed.JobId], T1.[VNA057VW01_Job_Not_Printed.KNDY4__Customer__c], T1.[VNA057VW01_Job_Not_Printed.CustomerName], T1.[VNA057VW01_Job_Not_Printed.SalesOrder], T1.[VNA057VW01_Job_Not_Printed.SalesOrderName])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS [VNA057VW01_Job_Not_Printed.JobTypeId], " & vbNewLine &
"            T.JobId AS [VNA057VW01_Job_Not_Printed.JobId], " & vbNewLine &
"            T.KNDY4CustomerC AS [VNA057VW01_Job_Not_Printed.KNDY4__Customer__c], " & vbNewLine &
"            T.CustomerName AS [VNA057VW01_Job_Not_Printed.CustomerName], " & vbNewLine &
"            T.SalesOrder AS [VNA057VW01_Job_Not_Printed.SalesOrder], " & vbNewLine &
"            T.SalesOrderName AS [VNA057VW01_Job_Not_Printed.SalesOrderName], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.ViewJobNotPrinteds AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.ViewJobNotPrinteds", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing ViewJobNotPrinteds" & vbNewLine &
"        [VNDataModel.ViewJobNotPrinted](T1.ViewJobNotPrinted_JobTypeId, T1.ViewJobNotPrinted_JobId, T1.ViewJobNotPrinted_KNDY4CustomerC, T1.ViewJobNotPrinted_CustomerName, T1.ViewJobNotPrinted_SalesOrder, T1.ViewJobNotPrinted_SalesOrderName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS ViewJobNotPrinted_JobTypeId, " & vbNewLine &
"            T.JobId AS ViewJobNotPrinted_JobId, " & vbNewLine &
"            T.KNDY4__Customer__c AS ViewJobNotPrinted_KNDY4CustomerC, " & vbNewLine &
"            T.CustomerName AS ViewJobNotPrinted_CustomerName, " & vbNewLine &
"            T.SalesOrder AS ViewJobNotPrinted_SalesOrder, " & vbNewLine &
"            T.SalesOrderName AS ViewJobNotPrinted_SalesOrderName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057VW01_Job_Not_Printeds AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057VW04_TypesWithNames", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057VW04_TypesWithNames" & vbNewLine &
"        [VNDataModel.Store.VNA057VW04_TypesWithNames](T1.[VNA057VW04_TypesWithNames.TypeCodeId], T1.[VNA057VW04_TypesWithNames.TypeCodeTypeId], T1.[VNA057VW04_TypesWithNames.TypeCode], T1.[VNA057VW04_TypesWithNames.TypeCodeName], T1.[VNA057VW04_TypesWithNames.TypeName])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeCodeId AS [VNA057VW04_TypesWithNames.TypeCodeId], " & vbNewLine &
"            T.TypeCodeTypeId AS [VNA057VW04_TypesWithNames.TypeCodeTypeId], " & vbNewLine &
"            T.TypeCode AS [VNA057VW04_TypesWithNames.TypeCode], " & vbNewLine &
"            T.TypeCodeName AS [VNA057VW04_TypesWithNames.TypeCodeName], " & vbNewLine &
"            T.TypeName AS [VNA057VW04_TypesWithNames.TypeName], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.TypesWithNames AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.TypesWithNames", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing TypesWithNames" & vbNewLine &
"        [VNDataModel.TypesWithName](T1.TypesWithName_TypeCodeId, T1.TypesWithName_TypeCodeTypeId, T1.TypesWithName_TypeCode, T1.TypesWithName_TypeCodeName, T1.TypesWithName_TypeName)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.TypeCodeId AS TypesWithName_TypeCodeId, " & vbNewLine &
"            T.TypeCodeTypeId AS TypesWithName_TypeCodeTypeId, " & vbNewLine &
"            T.TypeCode AS TypesWithName_TypeCode, " & vbNewLine &
"            T.TypeCodeName AS TypesWithName_TypeCodeName, " & vbNewLine &
"            T.TypeName AS TypesWithName_TypeName, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057VW04_TypesWithNames AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057VW05_Pallet_Jobs_Not_Printeds", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057VW05_Pallet_Jobs_Not_Printeds" & vbNewLine &
"        [VNDataModel.Store.VNA057VW05_Pallet_Jobs_Not_Printed](T1.[VNA057VW05_Pallet_Jobs_Not_Printed.JobTypeId], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.JobId], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.KNDY4__Customer__c], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.CustomerName], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.SalesOrder], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.SalesOrderName], T1.[VNA057VW05_Pallet_Jobs_Not_Printed.ShipmentData])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS [VNA057VW05_Pallet_Jobs_Not_Printed.JobTypeId], " & vbNewLine &
"            T.JobId AS [VNA057VW05_Pallet_Jobs_Not_Printed.JobId], " & vbNewLine &
"            T.KNDY4CustomerC AS [VNA057VW05_Pallet_Jobs_Not_Printed.KNDY4__Customer__c], " & vbNewLine &
"            T.CustomerName AS [VNA057VW05_Pallet_Jobs_Not_Printed.CustomerName], " & vbNewLine &
"            T.SalesOrder AS [VNA057VW05_Pallet_Jobs_Not_Printed.SalesOrder], " & vbNewLine &
"            T.SalesOrderName AS [VNA057VW05_Pallet_Jobs_Not_Printed.SalesOrderName], " & vbNewLine &
"            T.ShipmentData AS [VNA057VW05_Pallet_Jobs_Not_Printed.ShipmentData], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.ViewPalletJobsNotPrinteds AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.ViewPalletJobsNotPrinteds", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing ViewPalletJobsNotPrinteds" & vbNewLine &
"        [VNDataModel.ViewPalletJobsNotPrinted](T1.ViewPalletJobsNotPrinted_JobTypeId, T1.ViewPalletJobsNotPrinted_JobId, T1.ViewPalletJobsNotPrinted_KNDY4CustomerC, T1.ViewPalletJobsNotPrinted_CustomerName, T1.ViewPalletJobsNotPrinted_SalesOrder, T1.ViewPalletJobsNotPrinted_SalesOrderName, T1.ViewPalletJobsNotPrinted_ShipmentData)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeId AS ViewPalletJobsNotPrinted_JobTypeId, " & vbNewLine &
"            T.JobId AS ViewPalletJobsNotPrinted_JobId, " & vbNewLine &
"            T.KNDY4__Customer__c AS ViewPalletJobsNotPrinted_KNDY4CustomerC, " & vbNewLine &
"            T.CustomerName AS ViewPalletJobsNotPrinted_CustomerName, " & vbNewLine &
"            T.SalesOrder AS ViewPalletJobsNotPrinted_SalesOrder, " & vbNewLine &
"            T.SalesOrderName AS ViewPalletJobsNotPrinted_SalesOrderName, " & vbNewLine &
"            T.ShipmentData AS ViewPalletJobsNotPrinted_ShipmentData, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057VW05_Pallet_Jobs_Not_Printeds AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057VW12_Printers", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057VW12_Printers" & vbNewLine &
"        [VNDataModel.Store.VNA057VW12_Printers](T1.[VNA057VW12_Printers.LabelSizeName], T1.[VNA057VW12_Printers.LabelSizeCode], T1.[VNA057VW12_Printers.PrinterCompatibilityCode], T1.[VNA057VW12_Printers.PrinterCompatibilityName], T1.[VNA057VW12_Printers.SourceTypeCode], T1.[VNA057VW12_Printers.SourceTypeName], T1.[VNA057VW12_Printers.DeliveryTypeCode], T1.[VNA057VW12_Printers.DeliveryTypeName], T1.[VNA057VW12_Printers.PrinterName], T1.[VNA057VW12_Printers.AlternatePrinters], T1.[VNA057VW12_Printers.CompatibilityCode], T1.[VNA057VW12_Printers.PrinterID], T1.[VNA057VW12_Printers.SupportsSource], T1.[VNA057VW12_Printers.SupportsDelivery], T1.[VNA057VW12_Printers.SupportsSize], T1.[VNA057VW12_Printers.LastSize], T1.[VNA057VW12_Printers.LastSource], T1.[VNA057VW12_Printers.LastDelivery], T1.[VNA057VW12_Printers.Active])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.LabelSizeName AS [VNA057VW12_Printers.LabelSizeName], " & vbNewLine &
"            T.LabelSizeCode AS [VNA057VW12_Printers.LabelSizeCode], " & vbNewLine &
"            T.PrinterCompatibilityCode AS [VNA057VW12_Printers.PrinterCompatibilityCode], " & vbNewLine &
"            T.PrinterCompatibilityName AS [VNA057VW12_Printers.PrinterCompatibilityName], " & vbNewLine &
"            T.SourceTypeCode AS [VNA057VW12_Printers.SourceTypeCode], " & vbNewLine &
"            T.SourceTypeName AS [VNA057VW12_Printers.SourceTypeName], " & vbNewLine &
"            T.DeliveryTypeCode AS [VNA057VW12_Printers.DeliveryTypeCode], " & vbNewLine &
"            T.DeliveryTypeName AS [VNA057VW12_Printers.DeliveryTypeName], " & vbNewLine &
"            T.PrinterName AS [VNA057VW12_Printers.PrinterName], " & vbNewLine &
"            T.AlternatePrinters AS [VNA057VW12_Printers.AlternatePrinters], " & vbNewLine &
"            T.CompatibilityCode AS [VNA057VW12_Printers.CompatibilityCode], " & vbNewLine &
"            T.PrinterID AS [VNA057VW12_Printers.PrinterID], " & vbNewLine &
"            T.SupportsSource AS [VNA057VW12_Printers.SupportsSource], " & vbNewLine &
"            T.SupportsDelivery AS [VNA057VW12_Printers.SupportsDelivery], " & vbNewLine &
"            T.SupportsSize AS [VNA057VW12_Printers.SupportsSize], " & vbNewLine &
"            T.LastSize AS [VNA057VW12_Printers.LastSize], " & vbNewLine &
"            T.LastSource AS [VNA057VW12_Printers.LastSource], " & vbNewLine &
"            T.LastDelivery AS [VNA057VW12_Printers.LastDelivery], " & vbNewLine &
"            T.Active AS [VNA057VW12_Printers.Active], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.Printers AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.Printers", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing Printers" & vbNewLine &
"        [VNDataModel.Printer](T1.Printer_LabelSizeName, T1.Printer_LabelSizeCode, T1.Printer_PrinterCompatibilityCode, T1.Printer_PrinterCompatibilityName, T1.Printer_SourceTypeCode, T1.Printer_SourceTypeName, T1.Printer_DeliveryTypeCode, T1.Printer_DeliveryTypeName, T1.Printer_PrinterName, T1.Printer_AlternatePrinters, T1.Printer_CompatibilityCode, T1.Printer_PrinterID, T1.Printer_SupportsSource, T1.Printer_SupportsDelivery, T1.Printer_SupportsSize, T1.Printer_LastSize, T1.Printer_LastSource, T1.Printer_LastDelivery, T1.Printer_Active)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.LabelSizeName AS Printer_LabelSizeName, " & vbNewLine &
"            T.LabelSizeCode AS Printer_LabelSizeCode, " & vbNewLine &
"            T.PrinterCompatibilityCode AS Printer_PrinterCompatibilityCode, " & vbNewLine &
"            T.PrinterCompatibilityName AS Printer_PrinterCompatibilityName, " & vbNewLine &
"            T.SourceTypeCode AS Printer_SourceTypeCode, " & vbNewLine &
"            T.SourceTypeName AS Printer_SourceTypeName, " & vbNewLine &
"            T.DeliveryTypeCode AS Printer_DeliveryTypeCode, " & vbNewLine &
"            T.DeliveryTypeName AS Printer_DeliveryTypeName, " & vbNewLine &
"            T.PrinterName AS Printer_PrinterName, " & vbNewLine &
"            T.AlternatePrinters AS Printer_AlternatePrinters, " & vbNewLine &
"            T.CompatibilityCode AS Printer_CompatibilityCode, " & vbNewLine &
"            T.PrinterID AS Printer_PrinterID, " & vbNewLine &
"            T.SupportsSource AS Printer_SupportsSource, " & vbNewLine &
"            T.SupportsDelivery AS Printer_SupportsDelivery, " & vbNewLine &
"            T.SupportsSize AS Printer_SupportsSize, " & vbNewLine &
"            T.LastSize AS Printer_LastSize, " & vbNewLine &
"            T.LastSource AS Printer_LastSource, " & vbNewLine &
"            T.LastDelivery AS Printer_LastDelivery, " & vbNewLine &
"            T.Active AS Printer_Active, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057VW12_Printers AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntitiesStoreContainer.VNA057VW06_Job_Infos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing VNA057VW06_Job_Infos" & vbNewLine &
"        [VNDataModel.Store.VNA057VW06_Job_Info](T1.[VNA057VW06_Job_Info.JobTypeName], T1.[VNA057VW06_Job_Info.JobTypeId], T1.[VNA057VW06_Job_Info.KNDY4__Customer__c], T1.[VNA057VW06_Job_Info.Printed], T1.[VNA057VW06_Job_Info.KNDY4__Sales_Order__c], T1.[VNA057VW06_Job_Info.SalesOrderName], T1.[VNA057VW06_Job_Info.CustomerJobInfoId], T1.[VNA057VW06_Job_Info.CustomerName], T1.[VNA057VW06_Job_Info.CustomerShortName], T1.[VNA057VW06_Job_Info.PrinterCompatibilityID], T1.[VNA057VW06_Job_Info.LabelSizeId], T1.[VNA057VW06_Job_Info.SourceTypeId], T1.[VNA057VW06_Job_Info.DeliveryTypeId], T1.[VNA057VW06_Job_Info.LabelOrientationId], T1.[VNA057VW06_Job_Info.LabelCount], T1.[VNA057VW06_Job_Info.JobStepName], T1.[VNA057VW06_Job_Info.JobStepOrder], T1.[VNA057VW06_Job_Info.LabelType], T1.[VNA057VW06_Job_Info.Serialized], T1.[VNA057VW06_Job_Info.JobId], T1.[VNA057VW06_Job_Info.StepLabelCount], T1.[VNA057VW06_Job_Info.PrinterId], T1.[VNA057VW06_Job_Info.PrinterName], T1.[VNA057VW06_Job_Info.OverridePrinter], T1.[VNA057VW06_Job_Info.PrinterCompatibilityCode], T1.[VNA057VW06_Job_Info.LabelSizeCode], T1.[VNA057VW06_Job_Info.DeliveryTypeCode], T1.[VNA057VW06_Job_Info.LabelOrientationCode], T1.[VNA057VW06_Job_Info.SourceTypeCode], T1.[VNA057VW06_Job_Info.LabelTypeCode])" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeName AS [VNA057VW06_Job_Info.JobTypeName], " & vbNewLine &
"            T.JobTypeId AS [VNA057VW06_Job_Info.JobTypeId], " & vbNewLine &
"            T.KNDY4CustomerC AS [VNA057VW06_Job_Info.KNDY4__Customer__c], " & vbNewLine &
"            T.Printed AS [VNA057VW06_Job_Info.Printed], " & vbNewLine &
"            T.KNDY4SalesOrderC AS [VNA057VW06_Job_Info.KNDY4__Sales_Order__c], " & vbNewLine &
"            T.SalesOrderName AS [VNA057VW06_Job_Info.SalesOrderName], " & vbNewLine &
"            T.CustomerJobInfoId AS [VNA057VW06_Job_Info.CustomerJobInfoId], " & vbNewLine &
"            T.CustomerName AS [VNA057VW06_Job_Info.CustomerName], " & vbNewLine &
"            T.CustomerShortName AS [VNA057VW06_Job_Info.CustomerShortName], " & vbNewLine &
"            T.PrinterCompatibilityID AS [VNA057VW06_Job_Info.PrinterCompatibilityID], " & vbNewLine &
"            T.LabelSizeId AS [VNA057VW06_Job_Info.LabelSizeId], " & vbNewLine &
"            T.SourceTypeId AS [VNA057VW06_Job_Info.SourceTypeId], " & vbNewLine &
"            T.DeliveryTypeId AS [VNA057VW06_Job_Info.DeliveryTypeId], " & vbNewLine &
"            T.LabelOrientationId AS [VNA057VW06_Job_Info.LabelOrientationId], " & vbNewLine &
"            T.LabelCount AS [VNA057VW06_Job_Info.LabelCount], " & vbNewLine &
"            T.JobStepName AS [VNA057VW06_Job_Info.JobStepName], " & vbNewLine &
"            T.JobStepOrder AS [VNA057VW06_Job_Info.JobStepOrder], " & vbNewLine &
"            T.LabelType AS [VNA057VW06_Job_Info.LabelType], " & vbNewLine &
"            T.Serialized AS [VNA057VW06_Job_Info.Serialized], " & vbNewLine &
"            T.JobId AS [VNA057VW06_Job_Info.JobId], " & vbNewLine &
"            T.StepLabelCount AS [VNA057VW06_Job_Info.StepLabelCount], " & vbNewLine &
"            T.PrinterId AS [VNA057VW06_Job_Info.PrinterId], " & vbNewLine &
"            T.PrinterName AS [VNA057VW06_Job_Info.PrinterName], " & vbNewLine &
"            T.OverridePrinter AS [VNA057VW06_Job_Info.OverridePrinter], " & vbNewLine &
"            T.PrinterCompatibilityCode AS [VNA057VW06_Job_Info.PrinterCompatibilityCode], " & vbNewLine &
"            T.LabelSizeCode AS [VNA057VW06_Job_Info.LabelSizeCode], " & vbNewLine &
"            T.DeliveryTypeCode AS [VNA057VW06_Job_Info.DeliveryTypeCode], " & vbNewLine &
"            T.LabelOrientationCode AS [VNA057VW06_Job_Info.LabelOrientationCode], " & vbNewLine &
"            T.SourceTypeCode AS [VNA057VW06_Job_Info.SourceTypeCode], " & vbNewLine &
"            T.LabelTypeCode AS [VNA057VW06_Job_Info.LabelTypeCode], " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntities.JobInfos AS T" & vbNewLine &
"    ) AS T1"))
			cachedViews.Add("VNDataEntities.JobInfos", new DbMappingView("" & vbNewLine &
"    SELECT VALUE -- Constructing JobInfos" & vbNewLine &
"        [VNDataModel.JobInfo](T1.JobInfo_JobTypeName, T1.JobInfo_JobTypeId, T1.JobInfo_KNDY4CustomerC, T1.JobInfo_Printed, T1.JobInfo_KNDY4SalesOrderC, T1.JobInfo_SalesOrderName, T1.JobInfo_CustomerJobInfoId, T1.JobInfo_CustomerName, T1.JobInfo_CustomerShortName, T1.JobInfo_PrinterCompatibilityID, T1.JobInfo_LabelSizeId, T1.JobInfo_SourceTypeId, T1.JobInfo_DeliveryTypeId, T1.JobInfo_LabelOrientationId, T1.JobInfo_LabelCount, T1.JobInfo_JobStepName, T1.JobInfo_JobStepOrder, T1.JobInfo_LabelType, T1.JobInfo_Serialized, T1.JobInfo_JobId, T1.JobInfo_StepLabelCount, T1.JobInfo_PrinterId, T1.JobInfo_PrinterName, T1.JobInfo_OverridePrinter, T1.JobInfo_PrinterCompatibilityCode, T1.JobInfo_LabelSizeCode, T1.JobInfo_DeliveryTypeCode, T1.JobInfo_LabelOrientationCode, T1.JobInfo_SourceTypeCode, T1.JobInfo_LabelTypeCode)" & vbNewLine &
"    FROM (" & vbNewLine &
"        SELECT " & vbNewLine &
"            T.JobTypeName AS JobInfo_JobTypeName, " & vbNewLine &
"            T.JobTypeId AS JobInfo_JobTypeId, " & vbNewLine &
"            T.KNDY4__Customer__c AS JobInfo_KNDY4CustomerC, " & vbNewLine &
"            T.Printed AS JobInfo_Printed, " & vbNewLine &
"            T.KNDY4__Sales_Order__c AS JobInfo_KNDY4SalesOrderC, " & vbNewLine &
"            T.SalesOrderName AS JobInfo_SalesOrderName, " & vbNewLine &
"            T.CustomerJobInfoId AS JobInfo_CustomerJobInfoId, " & vbNewLine &
"            T.CustomerName AS JobInfo_CustomerName, " & vbNewLine &
"            T.CustomerShortName AS JobInfo_CustomerShortName, " & vbNewLine &
"            T.PrinterCompatibilityID AS JobInfo_PrinterCompatibilityID, " & vbNewLine &
"            T.LabelSizeId AS JobInfo_LabelSizeId, " & vbNewLine &
"            T.SourceTypeId AS JobInfo_SourceTypeId, " & vbNewLine &
"            T.DeliveryTypeId AS JobInfo_DeliveryTypeId, " & vbNewLine &
"            T.LabelOrientationId AS JobInfo_LabelOrientationId, " & vbNewLine &
"            T.LabelCount AS JobInfo_LabelCount, " & vbNewLine &
"            T.JobStepName AS JobInfo_JobStepName, " & vbNewLine &
"            T.JobStepOrder AS JobInfo_JobStepOrder, " & vbNewLine &
"            T.LabelType AS JobInfo_LabelType, " & vbNewLine &
"            T.Serialized AS JobInfo_Serialized, " & vbNewLine &
"            T.JobId AS JobInfo_JobId, " & vbNewLine &
"            T.StepLabelCount AS JobInfo_StepLabelCount, " & vbNewLine &
"            T.PrinterId AS JobInfo_PrinterId, " & vbNewLine &
"            T.PrinterName AS JobInfo_PrinterName, " & vbNewLine &
"            T.OverridePrinter AS JobInfo_OverridePrinter, " & vbNewLine &
"            T.PrinterCompatibilityCode AS JobInfo_PrinterCompatibilityCode, " & vbNewLine &
"            T.LabelSizeCode AS JobInfo_LabelSizeCode, " & vbNewLine &
"            T.DeliveryTypeCode AS JobInfo_DeliveryTypeCode, " & vbNewLine &
"            T.LabelOrientationCode AS JobInfo_LabelOrientationCode, " & vbNewLine &
"            T.SourceTypeCode AS JobInfo_SourceTypeCode, " & vbNewLine &
"            T.LabelTypeCode AS JobInfo_LabelTypeCode, " & vbNewLine &
"            True AS _from0" & vbNewLine &
"        FROM VNDataEntitiesStoreContainer.VNA057VW06_Job_Infos AS T" & vbNewLine &
"    ) AS T1"))
		End Sub
	End Class
End Namespace
