'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 7/9/2018 12:30:05 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    ''' <summary>
    ''' There are no comments for VNDataModel.JobInfo in the schema.
    ''' </summary>
    Public partial class JobInfo 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' There are no comments for JobTypeName in the schema.
        ''' </summary>
        Public Overridable Property JobTypeName() As String
    
        ''' <summary>
        ''' There are no comments for JobTypeId in the schema.
        ''' </summary>
        Public Overridable Property JobTypeId() As Integer
    
        ''' <summary>
        ''' There are no comments for KNDY4CustomerC in the schema.
        ''' </summary>
        Public Overridable Property KNDY4CustomerC() As String
    
        ''' <summary>
        ''' There are no comments for Printed in the schema.
        ''' </summary>
        Public Overridable Property Printed() As Boolean
    
        ''' <summary>
        ''' There are no comments for KNDY4SalesOrderC in the schema.
        ''' </summary>
        Public Overridable Property KNDY4SalesOrderC() As String
    
        ''' <summary>
        ''' There are no comments for SalesOrderName in the schema.
        ''' </summary>
        Public Overridable Property SalesOrderName() As String
    
        ''' <summary>
        ''' There are no comments for CustomerJobInfoId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobInfoId() As Integer
    
        ''' <summary>
        ''' There are no comments for CustomerName in the schema.
        ''' </summary>
        Public Overridable Property CustomerName() As String
    
        ''' <summary>
        ''' There are no comments for CustomerShortName in the schema.
        ''' </summary>
        Public Overridable Property CustomerShortName() As String
    
        ''' <summary>
        ''' There are no comments for PrinterCompatibilityID in the schema.
        ''' </summary>
        Public Overridable Property PrinterCompatibilityID() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelSizeId in the schema.
        ''' </summary>
        Public Overridable Property LabelSizeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for SourceTypeId in the schema.
        ''' </summary>
        Public Overridable Property SourceTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for DeliveryTypeId in the schema.
        ''' </summary>
        Public Overridable Property DeliveryTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelOrientationId in the schema.
        ''' </summary>
        Public Overridable Property LabelOrientationId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelCount in the schema.
        ''' </summary>
        Public Overridable Property LabelCount() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for JobStepName in the schema.
        ''' </summary>
        Public Overridable Property JobStepName() As String
    
        ''' <summary>
        ''' There are no comments for JobStepOrder in the schema.
        ''' </summary>
        Public Overridable Property JobStepOrder() As Integer
    
        ''' <summary>
        ''' There are no comments for LabelType in the schema.
        ''' </summary>
        Public Overridable Property LabelType() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for Serialized in the schema.
        ''' </summary>
        Public Overridable Property Serialized() As Global.System.Nullable(Of Boolean)
    
        ''' <summary>
        ''' There are no comments for JobId in the schema.
        ''' </summary>
        Public Overridable Property JobId() As Integer
    
        ''' <summary>
        ''' There are no comments for StepLabelCount in the schema.
        ''' </summary>
        Public Overridable Property StepLabelCount() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for PrinterId in the schema.
        ''' </summary>
        Public Overridable Property PrinterId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for PrinterName in the schema.
        ''' </summary>
        Public Overridable Property PrinterName() As String
    
        ''' <summary>
        ''' There are no comments for OverridePrinter in the schema.
        ''' </summary>
        Public Overridable Property OverridePrinter() As String
    
        ''' <summary>
        ''' There are no comments for PrinterCompatibilityCode in the schema.
        ''' </summary>
        Public Overridable Property PrinterCompatibilityCode() As String
    
        ''' <summary>
        ''' There are no comments for LabelSizeCode in the schema.
        ''' </summary>
        Public Overridable Property LabelSizeCode() As String
    
        ''' <summary>
        ''' There are no comments for DeliveryTypeCode in the schema.
        ''' </summary>
        Public Overridable Property DeliveryTypeCode() As String
    
        ''' <summary>
        ''' There are no comments for LabelOrientationCode in the schema.
        ''' </summary>
        Public Overridable Property LabelOrientationCode() As String
    
        ''' <summary>
        ''' There are no comments for SourceTypeCode in the schema.
        ''' </summary>
        Public Overridable Property SourceTypeCode() As String
    
        ''' <summary>
        ''' There are no comments for LabelTypeCode in the schema.
        ''' </summary>
        Public Overridable Property LabelTypeCode() As String
    
        ''' <summary>
        ''' There are no comments for FormatName in the schema.
        ''' </summary>
        Public Overridable Property FormatName() As String

        #End Region
    
        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
