'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 2022/06/29 2:44:18 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class ViewPrinter 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property LabelSizeName() As String
    
        Public Overridable Property LabelSizeCode() As String
    
        Public Overridable Property PrinterCompatibilityCode() As String
    
        Public Overridable Property PrinterCompatibilityName() As String
    
        Public Overridable Property SourceTypeCode() As String
    
        Public Overridable Property SourceTypeName() As String
    
        Public Overridable Property DeliveryTypeCode() As String
    
        Public Overridable Property DeliveryTypeName() As String
    
        Public Overridable Property PrinterName() As String
    
        Public Overridable Property AlternatePrinters() As String
    
        Public Overridable Property CompatibilityCode() As Integer
    
        Public Overridable Property PrinterID() As Integer
    
        Public Overridable Property SupportsSource() As Integer
    
        Public Overridable Property SupportsDelivery() As Integer
    
        Public Overridable Property SupportsSize() As Integer
    
        Public Overridable Property LastSize() As Integer?
    
        Public Overridable Property LastSource() As Integer?
    
        Public Overridable Property LastDelivery() As Integer?
    
        Public Overridable Property Active() As Boolean

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
