'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 2022/06/29 2:44:18 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class ViewSalesOrder 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property KNDY4StatusC() As String
    
        Public Overridable Property Name() As String
    
        Public Overridable Property SalesOrderId() As String
    
        Public Overridable Property SONo() As String
    
        Public Overridable Property ShipmentDate() As Global.System.DateTime?
    
        Public Overridable Property CustomerID() As String
    
        Public Overridable Property CustomerName() As String
    
        Public Overridable Property LineNo() As Decimal?
    
        Public Overridable Property ProductName() As String

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
