'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 6/25/2018 4:44:45 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    ''' <summary>
    ''' There are no comments for VNDataModel.CustomerJobStep in the schema.
    ''' </summary>
    Public partial class CustomerJobStep 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' There are no comments for CustomerJobStepsId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobStepsId() As Integer
    
        ''' <summary>
        ''' There are no comments for CustomerJobInfoId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobInfoId() As Integer
    
        ''' <summary>
        ''' There are no comments for JobStepId in the schema.
        ''' </summary>
        Public Overridable Property JobStepId() As Integer
    
        ''' <summary>
        ''' There are no comments for PrinterCompatibilityID in the schema.
        ''' </summary>
        Public Overridable Property PrinterCompatibilityID() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelSizeId in the schema.
        ''' </summary>
        Public Overridable Property LabelSizeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for SourceTypeId in the schema.
        ''' </summary>
        Public Overridable Property SourceTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for DeliveryTypeId in the schema.
        ''' </summary>
        Public Overridable Property DeliveryTypeId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelOrientationId in the schema.
        ''' </summary>
        Public Overridable Property LabelOrientationId() As Global.System.Nullable(Of Integer)
    
        ''' <summary>
        ''' There are no comments for LabelCount in the schema.
        ''' </summary>
        Public Overridable Property LabelCount() As Global.System.Nullable(Of Integer)

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' There are no comments for JobStep in the schema.
        ''' </summary>
        Public Overridable Property JobStep() As JobStep
    
        ''' <summary>
        ''' There are no comments for CustomerJobInfo in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobInfo() As CustomerJobInfo
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_PrinterCompatibilityID in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_PrinterCompatibilityID() As VNA057TB07TypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_LabelSizeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_LabelSizeId() As VNA057TB07TypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_SourceTypeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_SourceTypeId() As VNA057TB07TypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_DeliveryTypeId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_DeliveryTypeId() As VNA057TB07TypeCode
    
        ''' <summary>
        ''' There are no comments for VNA057TB07TypeCode_LabelOrientationId in the schema.
        ''' </summary>
        Public Overridable Property VNA057TB07TypeCode_LabelOrientationId() As VNA057TB07TypeCode

        #End Region
    
        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
