'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 3/15/2019 1:55:00 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class TableTypeCode 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property TypeCodeId() As Integer
    
        Public Overridable Property TypeCodeTypeId() As Integer
    
        Public Overridable Property TypeCode() As String
    
        Public Overridable Property TypeCodeName() As String

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property VNA057TB06Type() As TableType
    
        Public Overridable Property JobSteps() As ICollection(Of TableJobStep)
    
        Public Overridable Property CustomerJobSteps_PrinterCompatibilityID() As ICollection(Of TableCustomerJobStep)
    
        Public Overridable Property CustomerJobSteps_LabelSizeId() As ICollection(Of TableCustomerJobStep)
    
        Public Overridable Property CustomerJobSteps_SourceTypeId() As ICollection(Of TableCustomerJobStep)
    
        Public Overridable Property CustomerJobSteps_DeliveryTypeId() As ICollection(Of TableCustomerJobStep)
    
        Public Overridable Property CustomerJobSteps_LabelOrientationId() As ICollection(Of TableCustomerJobStep)

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
