'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 3/15/2019 1:55:00 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class TableCustomerJobInfo 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property CustomerJobInfoId() As Integer
    
        Public Overridable Property KNDY4CustomerC1() As String
    
        Public Overridable Property JobTypeId() As Integer
    
        Public Overridable Property CustNo() As String
    
        Public Overridable Property CustomerName() As String
    
        Public Overridable Property CustomerPrintName() As String
    
        Public Overridable Property CustomerShortName() As String
    
        Public Overridable Property Serialized() As Boolean?
    
        Public Overridable Property LabelPerLine() As Boolean?
    
        Public Overridable Property PrinterId() As Integer?
    
        Public Overridable Property NextUniqueLabelNo() As Integer? = 0
    
        Public Overridable Property DateCreated() As Global.System.DateTime?

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property JobType() As TableJobType
    
        Public Overridable Property Printer() As TablePrinter

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
