'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 2022/06/29 2:44:18 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class TableJobStep 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property JobStepId() As Integer
    
        Public Overridable Property JobTypeId() As Integer?
    
        Public Overridable Property JobStepName() As String
    
        Public Overridable Property JobStepOrder() As Integer
    
        Public Overridable Property LabelCount() As Integer?
    
        Public Overridable Property LabelType() As Integer?

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property JobType() As TableJobType
    
        Public Overridable Property CustomerJobSteps() As ICollection(Of TableCustomerJobStep)
    
        Public Overridable Property VNA057TB07TypeCode() As TableTypeCode

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
