'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 2022/06/29 2:44:18 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class ViewAllJob 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property JobId() As Integer
    
        Public Overridable Property KNDY4CustomerC() As String
    
        Public Overridable Property JobTypeId() As Integer
    
        Public Overridable Property Printed() As Boolean
    
        Public Overridable Property KNDY4SalesOrderC() As String
    
        Public Overridable Property SalesOrderName() As String
    
        Public Overridable Property JobTypeName() As String

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
