'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 3/15/2019 1:55:00 PM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    Public Partial Class TablePrinter 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        Public Overridable Property PrinterID() As Integer
    
        Public Overridable Property PrinterName() As String
    
        Public Overridable Property AlternatePrinters() As String
    
        Public Overridable Property CompatibilityCode() As Integer
    
        Public Overridable Property SupportsSource() As Integer
    
        Public Overridable Property SupportsDelivery() As Integer
    
        Public Overridable Property SupportsSize() As Integer
    
        Public Overridable Property LastSize() As Integer?
    
        Public Overridable Property LastSource() As Integer?
    
        Public Overridable Property LastDelivery() As Integer?
    
        Public Overridable Property Active() As Boolean

        #End Region
        #Region "Navigation Properties"
    
        Public Overridable Property CustomerJobInfos() As ICollection(Of TableCustomerJobInfo)

        #End Region

        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
