'------------------------------------------------------------------------------
' This is auto-generated code. 
'------------------------------------------------------------------------------
' This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
' Code is generated on: 12/3/2018 10:55:21 AM
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.Runtime.Serialization

Namespace VNDataModel

    ''' <summary>
    ''' There are no comments for VNDataModel.TableCustomerJobInfo in the schema.
    ''' </summary>
    Public partial class TableCustomerJobInfo 

        Public Sub New()
            OnCreated()
        End Sub

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' There are no comments for CustomerJobInfoId in the schema.
        ''' </summary>
        Public Overridable Property CustomerJobInfoId() As Integer
    
        ''' <summary>
        ''' There are no comments for KNDY4CustomerC1 in the schema.
        ''' </summary>
        Public Overridable Property KNDY4CustomerC1() As String
    
        ''' <summary>
        ''' There are no comments for JobTypeId in the schema.
        ''' </summary>
        Public Overridable Property JobTypeId() As Integer
    
        ''' <summary>
        ''' There are no comments for CustNo in the schema.
        ''' </summary>
        Public Overridable Property CustNo() As String
    
        ''' <summary>
        ''' There are no comments for CustomerName in the schema.
        ''' </summary>
        Public Overridable Property CustomerName() As String
    
        ''' <summary>
        ''' There are no comments for CustomerPrintName in the schema.
        ''' </summary>
        Public Overridable Property CustomerPrintName() As String
    
        ''' <summary>
        ''' There are no comments for CustomerShortName in the schema.
        ''' </summary>
        Public Overridable Property CustomerShortName() As String
    
        ''' <summary>
        ''' There are no comments for Serialized in the schema.
        ''' </summary>
        Public Overridable Property Serialized() As Boolean?
    
        ''' <summary>
        ''' There are no comments for LabelPerLine in the schema.
        ''' </summary>
        Public Overridable Property LabelPerLine() As Boolean?
    
        ''' <summary>
        ''' There are no comments for PrinterId in the schema.
        ''' </summary>
        Public Overridable Property PrinterId() As Integer?
    
        ''' <summary>
        ''' There are no comments for NextUniqueLabelNo in the schema.
        ''' </summary>
        Public Overridable Property NextUniqueLabelNo() As Integer? = 0
    
        ''' <summary>
        ''' There are no comments for DateCreated in the schema.
        ''' </summary>
        Public Overridable Property DateCreated() As Global.System.DateTime?

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' There are no comments for JobType in the schema.
        ''' </summary>
        Public Overridable Property JobType() As TableJobType
    
        ''' <summary>
        ''' There are no comments for Printer in the schema.
        ''' </summary>
        Public Overridable Property Printer() As TablePrinter

        #End Region
    
        #Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
        #End Region
    End Class

End Namespace
